USE railway;

CREATE TABLE Usuarios (
  id_usuario INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  vc_username VARCHAR(255) NOT NULL,
  vc_password VARCHAR(255) NOT NULL,
  vc_nombre VARCHAR(255) NOT NULL,
  b_activo BOOLEAN NOT NULL DEFAULT TRUE,
  dt_registro INT(11) UNSIGNED NOT NULL DEFAULT 0,
  dt_actualizacion INT(11) UNSIGNED NOT NULL DEFAULT 0
);
