USE railway;

CREATE TABLE usuarios (
  id_usuario INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  vc_username VARCHAR(255) NOT NULL,
  vc_password VARCHAR(255) NOT NULL,
  vc_nombre VARCHAR(255) NOT NULL,
  b_activo BOOLEAN NOT NULL DEFAULT TRUE,
  dt_registro INT(11) UNSIGNED NOT NULL DEFAULT 0,
  dt_actualizacion INT(11) UNSIGNED NOT NULL DEFAULT 0,
  id_negocio INT(11) UNSIGNED NOT NULL DEFAULT 0,
);

CREATE TABLE cuentas_promotores (
  id_cuenta INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_promotor INT(11) UNSIGNED NOT NULL,
  dc_saldo_actual DECIMAL(21,6) NOT NULL DEFAULT 0.000000,
  dc_saldo_disponible DECIMAL(21,6) NOT NULL DEFAULT 0.000000,
  dc_saldo_pendiente DECIMAL(21,6) NOT NULL DEFAULT 0.000000,
  vc_moneda VARCHAR(3) NOT NULL DEFAULT 'MXN',
  b_activa BOOLEAN NOT NULL DEFAULT TRUE,
  dt_creacion INT(11) UNSIGNED NOT NULL DEFAULT 0,
  dt_actualizacion INT(11) UNSIGNED NOT NULL DEFAULT 0,
);
